import { ThemeContext } from "@/context/ThemeProvider";
import useTheme, { THEME } from "@/foundations/Theme/useTheme";
import Head from "next/head";
import { useContext } from "react";

export default function Home() {
  const { theme, setTheme } = useContext(ThemeContext);
  function handleOnClickThemeButton() {
    if (theme === THEME.LIGHT) setTheme(THEME.DARK);
    if (theme === THEME.DARK) setTheme(THEME.LIGHT);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={handleOnClickThemeButton}>Here</button>
      </main>
    </>
  );
}
