import ImageCard from "@/components/atoms/ImageCard/ImageCard";
import Spinner from "@/components/atoms/Spinner/Spinner";
import ImagesContainer from "@/components/organisms/ImagesContainer/ImagesContainer";
import Navbar from "@/components/organisms/Navbar/Navbar";
import useTheme from "@/foundations/Theme/useTheme";
import useImagesCardsData from "@/services/useImagesCardsData";

import Head from "next/head";

export default function Home() {
  const theme = useTheme();

  const imagesCardsResponse = useImagesCardsData();

  if (imagesCardsResponse.isLoading)
    return (
      <div
        style={{
          backgroundColor: theme.bg,
          height: "100dvh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}>
        <Spinner />
      </div>
    );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main
        style={{
          padding: "2em 5em 2em 5em",
          height: "100dvh",
          display: "flex",
          flexDirection: "column",
          backgroundColor: theme.bg,
        }}>
        <ImagesContainer>
          {!imagesCardsResponse.isLoading &&
            imagesCardsResponse.data?.map((imageData) => (
              <ImageCard key={imageData.id} imageData={imageData} />
            ))}
        </ImagesContainer>
      </main>
    </>
  );
}
